### ISSUE TITLE
Dormitory choice can't be "no" if the orchestra said yes

### ISSUE THREAD

**Issue by ljukas** [studentorkesterfestivalen/sof-dbapp#15]
If the orchestra chooses to use dormitory, a participant in this orchestra cant NOT choose dormitory, even if they choose no.

**Comment by patriksletmo** [comment]
Issue present [here](https://github.com/studentorkesterfestivalen/sof-dbapp/blob/master/app/models/orchestra_signup.rb#L21). Should check for nil and not nullable.
